### ISSUE TITLE
configure git workflow to autogenerate task branch

### ISSUE THREAD

**Issue by rakshyak-98** [rakshyak-98/pokemon-card-game#3]
##  Task Reference

- [work flow doc](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows)
- [github secrets](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository)
- [project card event](https://docs.github.com/en/webhooks/webhook-events-and-payloads#project_card)
- [workflow syntax](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows)

## Requirements

- [ ] when a new Todo task is created an issue will be created with a branch related to the issue.
- [ ] setup github > settings secrets
- [ ] when a issue is created auto include a ISSUE_TEMPLATE with (requirement, references)
- [ ] fix workflow changes [action ref](https://github.com/rakshyak-98/pokemon-card-game/actions/runs/11191550533)

### Workflow Breakdown:
1. **Trigger**: When a task is moved to the **"In Progress"** section of **GitHub Projects**.
2. **Create an Issue**: 
   - The issue title will be the same as the task title.
   - The issue will be automatically assigned to the person who moved the task.
3. **Create a Branch**:
   - The branch name will follow your naming convention and will use the issue title.
