### ISSUE TITLE
create Player interface

### ISSUE THREAD

**Issue by rakshyak-98** [rakshyak-98/pokemon-card-game#6]
## Task Reference
- [ui template](https://www.topdecked.com/collection/88312b65-e51d-4e59-a84f-c13dbf7b9c33(detail:cards/details/mmq/61/Brainstorm)?i=0&s=binder-cards&refId=ad85c8ee-9c4e-419a-8aaa-c55fbf3acc5c)
- [ui liberary](https://ui.shadcn.com/docs/installation/vite)

## Requirements
- [x] create my cards view for player
- [x] create side bar navigation
- [x] create search card by name
- [x] create user login and sign up
